#!/bin/bash

bspc config window_gap   8
bspc config border_width 4

#bspc config top_padding 16

bspc config active_border_color  "#00FFFFFF"
bspc config normal_border_color  "#00FFFFFF"
bspc config focused_border_color "#00FFFFFF"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_size
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4

