#!/usr/bin/env bash

NOTE_FILE="${NOTE_FILE/#\~/$HOME}"

if [ ! -f $NOTE_FILE ]; then
    echo "Could not find ${NOTE_FILE}."
    exit 1
fi

if [ -z "$EDITOR" ]; then
    echo '$EDITOR not set'
    exit 1
fi

"$EDITOR" "$NOTE_FILE"
