#!/usr/bin/env bash

# TODO: on some systems, the md5 command is `md5sum`. Make the script try both
# options and give up if neither can be found.

# Command line argument passed. Parse just one line
if [ ! -z "$1" ]; then
    line=$*
    line_length=${#line}
    hash_length=9 # example: (#345678)
    padding=$(expr 80 - $line_length)
    md5hash=$(echo \(\#$(echo -n "$line" | md5 | cut -b 1-6)\))
    printf '%s%*s\n' "$line" $padding $md5hash
    exit 0
fi

# Coming from vim, probably
while read line
do
    line_length=${#line}
    hash_length=9 # example: (#345678)
    padding=$(expr 80 - $line_length)
    md5hash=$(echo \(\#$(echo -n "$line" | md5 | cut -b 1-6)\))
    printf '%s%*s\n' "$line" $padding $md5hash
done
