#!/bin/bash

usage(){
  echo "usage: $(basename $0) <repeat_every> <regex> command..."
  echo "example: $(basename $0) 1 '01:01.*AM UTC' 'date'"
}

sleep_error_msg() {
  echo "$(basename $0): invalid time interval '$1'"
}

if [[ ! $# -eq 3 ]]; then
  usage
  exit 1
fi

sleep_time="$1"
regex="$2"
shift 2

while true
do
  eval "$@" 2>&1 | tee /dev/tty | grep -E "$regex" &>/dev/null && exit 0
  sleep "$sleep_time" &>/dev/null || { sleep_error_msg "$@" && exit 1; }
done
