#!/bin/bash

# BUG: all matching sections are printed instead of listing sections

export defn="$1"
export targ="$2"

if [ -z "$targ" ]; then
    script=$(envsubst <<< '/$defn/ {print}')
    awk "$script" - ; exit $?
fi

#input=$(cat)
#
#matches=$(awk "$(envsubst <<< '/$defn/ && /$targ/ {print}')" <<< $Input)
#matchesCount=$(wc -l <<< matches)
#if [ "$matchesCount" -gt 1 ]; then
#  echo "$matches"
#  exit 1
#fi

script=$(envsubst <<< '
  /$defn/ && /$targ/        {state="FOUND"; print; next}
  /$defn/ && state=="FOUND" {exit 0}
  /$defn/                   {state="NFOUND"; next}
  state=="FOUND"            {print}')

awk "$script" - ; exit $?
