#!/bin/bash

export defn="$1"
export targ="$2"

if [ -z "$targ" ]; then
    script=$(envsubst <<< '/$defn/ {print}')
    awk "$script" - ; exit $?
fi

script=$(envsubst <<< '
  /$defn/ && found==1             {end_section="true"}              # comment
  found>0   && /$defn/ && /$targ/ {headers[++found]=$0; next}       # multiple sections found; just add header
  found=="" && /$defn/ && /$targ/ {headers[++found]=$0}             #
  found==1 && end_section!="true" {content[++contentNum]=$0; next}  #

  END {
    if(length(headers)>1) for (i=1; i <= length(headers); i++) print headers[i]
    else                  for (i=1; i <= length(content); i++) print content[i]
  }
')

awk "$script" - ; exit $?
