#!/bin/bash

export defn="$1" # section definition
export targ="$2" # section target

if [ -z "$targ" ]; then
    script=$(envsubst <<< '/$defn/ {print}') # no target; just show section headers
    awk "$script" - ; exit $?
fi

script=$(envsubst <<< '
  /$defn/  && found==1 {end="true"}             # end of target section
  /$defn/  && /$targ/  {headers[++found]=$0}    # found matching section
  found==1 && end==""  {content[++cIter]=$0}    # store content of section

  END {
    if (found>1) {print_array(headers); exit 1} # more than one section found
    else         {print_array(content); exit 0} # print only found section
  }
  function print_array(a) { for (i=1; i<=length(a); i++) print a[i] }
')

awk "$script" - ; exit $?
