#!/bin/bash

# TODO: add comments
# TODO: add ,sessions script which should list all active session names
# TODO: make this script use ,sessions to check that session does not already exist
# TODO: make ,session-delete ,sessions before delete

if [ -z $2 ]; then
  echo Usage: $0 git_repo session_name
  exit 1
fi

git_repo=$1
session_name=$2

mkdir ~/.sessions >& /dev/null
working_dir=~/.sessions/${session_name}

git clone git@github.com:brandonpaiz/${git_repo}.git $working_dir
pushd $working_dir
git remote add upstream https://github.com/grpc/${git_repo}.git
git fetch upstream
git merge master upstream/master
git checkout -b ${session_name}
git push -u origin HEAD

tmux new-session -d -s ${session_name} # create tmux session without attaching to it

tmux switch -t ${session_name} || tmux attach -t ${session_name}

